[workspace]
resolver = "2"
members = [
    "projects/crates/notedown-ir",
    "projects/crates/notedown-formats",
]
default-members = [
    "projects/crates/notedown-ir",
    "projects/crates/notedown-formats",
]
exclude = []

[workspace.dependencies]
notedown-ir = { path = "projects/crates/notedown-ir" }
notedown-formats = { path = "projects/crates/notedown-formats" }

oak-core = { git = "https://github.com/yggdrasil-language/oak.rs.git", branch = "dev" }
oak-markdown = { git = "https://github.com/yggdrasil-language/oak.rs.git", branch = "dev", default-features = false, features = ["serde"] }
oak-notedown = { git = "https://github.com/yggdrasil-language/oak.rs.git", branch = "dev", default-features = false, features = ["serde"] }
oak-html = { git = "https://github.com/yggdrasil-language/oak.rs.git", branch = "dev", default-features = false, features = ["serde"] }
oak-xml = { git = "https://github.com/yggdrasil-language/oak.rs.git", branch = "dev", default-features = false, features = ["serde"] }
oak-testing = { git = "https://github.com/yggdrasil-language/oak.rs.git", branch = "dev" }

acorn-core = { git = "https://github.com/yggdrasil-language/acorn.rs.git", branch = "dev" }
acorn-cfb = { git = "https://github.com/yggdrasil-language/acorn.rs.git", branch = "dev" }
acorn-doc = { git = "https://github.com/yggdrasil-language/acorn.rs.git", branch = "dev" }
acorn-docx = { git = "https://github.com/yggdrasil-language/acorn.rs.git", branch = "dev" }
acorn-epub = { git = "https://github.com/yggdrasil-language/acorn.rs.git", branch = "dev" }

[profile.release]
lto = true
opt-level = "s"
