[package]
name = "notedown_parser"
version = "0.12.0"
authors = ["Aster <192607617↯qq.com>"]
description = "Notedown Text parser"
repository = "https://github.com/notedge/notedown-rs"
readme = "../../readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
arcstr = "*"

[dependencies.notedown_ast]
workspace = true

[dependencies.notedown-error]
workspace = true



[dev-dependencies]
