name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [macos-latest, windows-latest]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Tests
        run: cargo test -p notedown-ir -p notedown-formats --release
